#!/usr/bin/env tsx
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(__dirname, "..");
const DEPLOYMENTS = join(ROOT, "contracts/deployments/sepolia");
const OUT_DIR = join(ROOT, "web/lib");
const OUT = join(OUT_DIR, "contracts.ts");

if (!existsSync(DEPLOYMENTS)) {
  console.error(`No deployments found at ${DEPLOYMENTS}. Run \`pnpm deploy:sepolia\` first.`);
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });

function load(name: string): { address: `0x${string}`; abi: unknown[] } {
  const path = join(DEPLOYMENTS, `${name}.json`);
  const json = JSON.parse(readFileSync(path, "utf8"));
  return { address: json.address, abi: json.abi };
}

const registry = load("AgentRegistry");
const router = load("ConfidentialPaymentRouter");

const cUSDTAddress =
  process.env.CUSDT_SEPOLIA ?? "0x4E7B06D78965594eB5EF5414c357ca21E1554491";

const out = `// AUTO-GENERATED by scripts/copy-abi.ts. Do not edit by hand.
export const REGISTRY_ADDRESS = "${registry.address}" as const;
export const ROUTER_ADDRESS = "${router.address}" as const;
export const CUSDT_ADDRESS = "${cUSDTAddress}" as const;

export const REGISTRY_ABI = ${JSON.stringify(registry.abi, null, 2)} as const;
export const ROUTER_ABI = ${JSON.stringify(router.abi, null, 2)} as const;
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT}`);
